(() => {
  "use strict";
  const CLOUD_TABLE="printora_materials", CLOUD_SOURCE="v40.1", LOCAL_PREFIX="printora_materials_v1::";
  const $=id=>document.getElementById(id);
  const num=v=>{const n=Number(String(v??"").replace(/\s/g,"").replace(/,/g,"."));return Number.isFinite(n)?n:0;};
  const normName=v=>String(v??"").trim().replace(/\s+/g," ");
  let client=null,userId=null,materials=[],editingId=null,saving=false;
  function getClient(){client=window.PRINTCALC_AUTH_CORE?.getClient?.()||null;return client;}
  async function getUser(){const c=getClient();if(!c)return null;try{return(await c.auth.getSession())?.data?.session?.user||null;}catch(_){return null;}}
  function key(){return `${LOCAL_PREFIX}${userId||"guest"}`;}
  function normalize(item={}){return{id:String(item.id||`material-${Date.now()}-${Math.random().toString(36).slice(2,8)}`),name:normName(item.name),type:normName(item.type)||"Материал",lengthM:num(item.lengthM),widthMm:num(item.widthMm),priceM2:num(item.priceM2),cloudId:item.cloudSource===CLOUD_SOURCE?(item.cloudId||null):null,cloudSource:item.cloudSource===CLOUD_SOURCE?CLOUD_SOURCE:"",createdAt:item.createdAt||new Date().toISOString()};}
  function dedupe(list){const map=new Map();for(const raw of list||[]){const m=normalize(raw);if(!m.name)continue;const k=m.name.toLocaleLowerCase("ru-RU");const old=map.get(k);if(!old||(m.cloudSource===CLOUD_SOURCE&&old.cloudSource!==CLOUD_SOURCE))map.set(k,m);}return[...map.values()];}
  function saveLocal(){try{materials=dedupe(materials);localStorage.setItem(key(),JSON.stringify(materials));return true;}catch(_){return false;}}
  function loadLocal(){try{materials=dedupe(JSON.parse(localStorage.getItem(key())||"[]"));saveLocal();}catch(_){materials=[];}}
  async function loadCloud(){const c=getClient();if(!c||!userId)return;const all=[];let from=0;const page=500;while(true){const r=await c.from(CLOUD_TABLE).select("id,user_id,name,data,created_at,updated_at").eq("user_id",userId).order("created_at",{ascending:true}).range(from,from+page-1);if(r.error)throw r.error;for(const row of r.data||[])all.push(normalize({...row.data,name:row.name,cloudId:row.id,cloudSource:CLOUD_SOURCE,createdAt:row.created_at}));if((r.data||[]).length<page)break;from+=page;}const pending=materials.filter(m=>m.cloudSource!==CLOUD_SOURCE);materials=dedupe([...all,...pending]);saveLocal();renderList();populateSelect();window.dispatchEvent(new CustomEvent("printora:materials-ready",{detail:materials.slice()}));}
  async function cloudInsert(m){const c=getClient();if(!c||!userId)throw new Error("Войдите в аккаунт, чтобы сохранить материал в облаке.");const r=await c.from(CLOUD_TABLE).insert({user_id:userId,name:m.name,data:{id:m.id,name:m.name,type:m.type,lengthM:m.lengthM,widthMm:m.widthMm,priceM2:m.priceM2,createdAt:m.createdAt}}).select("id,user_id,name,data,created_at").single();if(r.error){if(r.error.code==="23505"){const q=await c.from(CLOUD_TABLE).select("id,user_id,name,data,created_at").eq("user_id",userId).eq("name_key",m.name.toLocaleLowerCase("ru-RU")).maybeSingle();if(!q.error&&q.data?.id){const cloud=normalize({...q.data.data,name:q.data.name,cloudId:q.data.id,cloudSource:CLOUD_SOURCE,createdAt:q.data.created_at});Object.assign(m,cloud);return m;}}throw r.error;}if(!r.data?.id||r.data.user_id!==userId)throw new Error("Материал создан, но облако не подтвердило владельца.");m.cloudId=r.data.id;m.cloudSource=CLOUD_SOURCE;return m;}
  async function cloudUpdate(m){const c=getClient();if(!c||!userId||!m.cloudId||m.cloudSource!==CLOUD_SOURCE)throw new Error("Облачная запись материала не найдена.");const r=await c.from(CLOUD_TABLE).update({name:m.name,data:{id:m.id,name:m.name,type:m.type,lengthM:m.lengthM,widthMm:m.widthMm,priceM2:m.priceM2,createdAt:m.createdAt,updatedAt:new Date().toISOString()}}).eq("id",m.cloudId).eq("user_id",userId).select("id,user_id,name,data,created_at").maybeSingle();if(r.error)throw r.error;if(!r.data?.id)throw new Error("Изменение материала не подтверждено облаком.");return m;}
  async function cloudDelete(m){const c=getClient();if(!c||!userId||!m.cloudId||m.cloudSource!==CLOUD_SOURCE)return;const r=await c.from(CLOUD_TABLE).delete().eq("id",m.cloudId).eq("user_id",userId).select("id");if(r.error)throw r.error;if(!r.data?.length)throw new Error("Удаление материала не подтверждено облаком.");}
  function modalHtml(){return `<div class="pc-material-manager-card-v40" role="dialog" aria-modal="true"><button type="button" class="pc-material-manager-close-v40" data-close aria-label="Закрыть">×</button><div class="eyebrow">СПРАВОЧНИК</div><h2>Мои материалы</h2><p>Один справочник для быстрого и детального расчёта. Данные привязаны к аккаунту.</p><div class="pc-material-manager-toolbar-v40"><input id="pc-material-search-v36" type="search" placeholder="Найти материал…" autocomplete="off"><span id="pc-material-count-v36">0 из 0</span></div><div id="pc-material-list-v36" class="pc-material-list-v36"></div><div class="pc-material-manager-actions-v40"><button type="button" class="secondary" data-close>Закрыть</button><button type="button" class="primary" data-add>+ ДОБАВИТЬ МАТЕРИАЛ</button></div></div>`;}
  function ensureManager(){let modal=$("pc-material-manager-v40");if(modal)return modal;modal=document.createElement("div");modal.id="pc-material-manager-v40";modal.className="pc-material-manager-v40";modal.hidden=true;modal.innerHTML=modalHtml();document.body.appendChild(modal);modal.addEventListener("click",e=>{if(e.target===modal||e.target.closest("[data-close]"))modal.hidden=true;if(e.target.closest("[data-add]")){e.preventDefault();openModal();}});$("pc-material-search-v36")?.addEventListener("input",renderList);return modal;}
  function message(text,type=""){const el=$("pc-material-message-v36");if(el){el.textContent=text;el.className=`pc-material-message-v36 ${type}`;}}
  function field(id,value){const el=$(id);if(el)el.value=value??"";}
  function ensureEditModal(){if($("pc-material-modal-v36"))return;const modal=document.createElement("div");modal.id="pc-material-modal-v36";modal.className="pc-material-modal-v36";modal.hidden=true;modal.innerHTML=`<div class="pc-material-modal-card-v36" role="dialog" aria-modal="true"><button type="button" class="pc-material-close-v36" data-close aria-label="Закрыть">×</button><div class="pc-material-eyebrow-v36">МОИ МАТЕРИАЛЫ</div><h2 id="pc-material-title-v36">Добавить материал</h2><p>Заполните название, ширину и цену материала.</p><div id="pc-material-message-v36"></div><div class="pc-material-form-grid-v36"><label><span>Название материала</span><input id="pc-material-name-v36" type="text" maxlength="100" placeholder="PP 50 мкм"></label><label><span>Тип</span><input id="pc-material-type-v36" type="text" maxlength="60" placeholder="Плёнка, бумага…"></label><label><span>Длина, м</span><input id="pc-material-length-v36" type="number" min="0" step="0.1" placeholder="1000"></label><label><span>Ширина, мм</span><input id="pc-material-width-v36" type="number" min="0" step="0.1" placeholder="300"></label><label><span>Цена материала, ₽/м²</span><input id="pc-material-price-v36" type="number" min="0" step="0.01" placeholder="68"></label></div><div class="pc-material-actions-v36"><button type="button" data-close>Отмена</button><button type="button" id="pc-material-save-v36">Сохранить материал</button></div></div>`;document.body.appendChild(modal);modal.addEventListener("click",e=>{if(e.target===modal||e.target.closest("[data-close]"))closeModal();});$("pc-material-save-v36")?.addEventListener("click",saveForm);}
  function openModal(materialId=null){ensureEditModal();editingId=materialId;const m=materialId?materials.find(x=>x.id===materialId):null;if(materialId&&!m)return;$("pc-material-title-v36").textContent=m?"Изменить материал":"Добавить материал";$("pc-material-save-v36").textContent=m?"Сохранить изменения":"Сохранить материал";field("pc-material-name-v36",m?.name||"");field("pc-material-type-v36",m?.type||"Материал");field("pc-material-length-v36",m?.lengthM||"");field("pc-material-width-v36",m?.widthMm||"");field("pc-material-price-v36",m?.priceM2||"");message("");$("pc-material-modal-v36").hidden=false;setTimeout(()=>$("pc-material-name-v36")?.focus(),30);}
  function closeModal(){const m=$("pc-material-modal-v36");if(m)m.hidden=true;editingId=null;}
  async function saveForm(){if(saving)return;const name=normName($("pc-material-name-v36")?.value),type=normName($("pc-material-type-v36")?.value)||"Материал",lengthM=num($("pc-material-length-v36")?.value),widthMm=num($("pc-material-width-v36")?.value),priceM2=num($("pc-material-price-v36")?.value);if(!name)return message("Укажите название материала.","error");if(widthMm<=0)return message("Укажите ширину материала больше нуля.","error");if(priceM2<=0)return message("Укажите цену материала больше нуля.","error");if(!userId)userId=(await getUser())?.id||null;if(!userId)return message("Войдите в аккаунт, чтобы материал синхронизировался между устройствами.","error");const duplicate=materials.some(x=>x.id!==editingId&&x.name.toLocaleLowerCase("ru-RU")===name.toLocaleLowerCase("ru-RU"));if(duplicate)return message("Материал с таким названием уже есть.","error");saving=true;const btn=$("pc-material-save-v36");if(btn){btn.disabled=true;btn.textContent="Сохраняем…";}try{let saved;if(editingId){const old=materials.find(x=>x.id===editingId);saved=normalize({...old,name,type,lengthM,widthMm,priceM2});materials=materials.map(x=>x.id===editingId?saved:x);saveLocal();if(saved.cloudSource===CLOUD_SOURCE){try{await cloudUpdate(saved);}catch(error){window.dispatchEvent(new CustomEvent("printora:cloud-error",{detail:{error,context:"Материал"}}));}}else{try{saved=await cloudInsert(saved);}catch(error){window.dispatchEvent(new CustomEvent("printora:cloud-error",{detail:{error,context:"Материал"}}));}materials=materials.map(x=>x.id===saved.id?saved:x);saveLocal();}}else{saved=normalize({name,type,lengthM,widthMm,priceM2});materials.push(saved);saveLocal();try{saved=await cloudInsert(saved);}catch(error){window.dispatchEvent(new CustomEvent("printora:cloud-error",{detail:{error,context:"Материал"}}));}materials=materials.map(x=>x.id===saved.id?saved:x);saveLocal();}renderList();populateSelect();closeModal();window.dispatchEvent(new CustomEvent("printora:material-saved",{detail:saved}));}catch(error){message(window.PRINTORA_FRIENDLY_ERROR?.(error)||error?.message||"Не удалось сохранить материал.","error");}finally{if(btn){btn.disabled=false;btn.textContent="Сохранить материал";}saving=false;}}
  async function removeMaterial(id){const m=materials.find(x=>x.id===id);if(!m)return;if(!confirm(`Удалить материал «${m.name}»?`))return;try{await cloudDelete(m);materials=materials.filter(x=>x.id!==id);saveLocal();renderList();populateSelect();}catch(error){message(window.PRINTORA_FRIENDLY_ERROR?.(error)||error?.message||"Не удалось удалить материал.","error");}}
  function renderList(){const box=$("pc-material-list-v36");if(!box)return;const q=($("pc-material-search-v36")?.value||"").trim().toLocaleLowerCase("ru-RU");const rows=q?materials.filter(m=>`${m.name} ${m.type}`.toLocaleLowerCase("ru-RU").includes(q)):materials;const count=$("pc-material-count-v36");if(count)count.textContent=`${rows.length} из ${materials.length}`;if(!rows.length){box.innerHTML=`<div class="pc-material-empty-v36"><strong>${materials.length?"Материал не найден":"Добавьте первый материал"}</strong><span>${materials.length?"Измените поиск.":"После добавления он появится здесь и в калькуляторах."}</span></div>`;return;}const e=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));box.innerHTML=rows.map(m=>`<article class="pc-material-card-v36"><div><small>${e(m.type)}</small><h3>${e(m.name)}</h3></div><div class="pc-material-card-metrics-v36"><div><span>Длина</span><b>${m.lengthM?m.lengthM.toLocaleString("ru-RU"):"—"}</b><small>м</small></div><div><span>Ширина</span><b>${m.widthMm.toLocaleString("ru-RU")}</b><small>мм</small></div><div><span>Цена</span><b>${m.priceM2.toLocaleString("ru-RU",{maximumFractionDigits:2})}</b><small>₽/м²</small></div></div><div class="pc-material-card-actions-v36"><button type="button" data-material-edit="${e(m.id)}">Изменить</button><button type="button" data-material-delete="${e(m.id)}">Удалить</button></div></article>`).join("");box.querySelectorAll("[data-material-edit]").forEach(b=>b.onclick=()=>openModal(b.dataset.materialEdit));box.querySelectorAll("[data-material-delete]").forEach(b=>b.onclick=()=>removeMaterial(b.dataset.materialDelete));}
  function populateSelect(){const select=$("materialSelect");if(!select)return;const current=select.value;select.innerHTML=`<option value="">Без выбора материала — ввести цену вручную</option>`+materials.map(m=>`<option value="${m.id}">${m.name} — ${m.widthMm.toLocaleString("ru-RU")} мм — ${m.priceM2.toLocaleString("ru-RU",{maximumFractionDigits:2})} ₽/м²</option>`).join("");if(materials.some(m=>m.id===current))select.value=current;}
  function onSelect(){const id=$("materialSelect")?.value||"",m=materials.find(x=>x.id===id)||null;window.PRINTORA_MATERIAL=m?{id:m.id,name:m.name,widthMm:m.widthMm,lengthM:m.lengthM,priceM2:m.priceM2}:null;if(m){if($("web"))$("web").value=m.widthMm;if($("matPrice"))$("matPrice").value=m.priceM2;}$("materialPreview-v36")?.removeAttribute("hidden");const pn=$("materialPreviewName-v36"),pw=$("materialPreviewWidth-v36"),pl=$("materialPreviewLength-v36"),pp=$("materialPreviewPrice-v36");if(m){if(pn)pn.textContent=m.name;if(pw)pw.textContent=`${m.widthMm.toLocaleString("ru-RU")} мм`;if(pl)pl.textContent=m.lengthM?`${m.lengthM.toLocaleString("ru-RU")} м`:"—";if(pp)pp.textContent=`${m.priceM2.toLocaleString("ru-RU",{maximumFractionDigits:2})} ₽/м²`;}else{$("materialPreview-v36")?.setAttribute("hidden","");}}
  async function init(){userId=(await getUser())?.id||null;loadLocal();ensureManager();if(userId){try{await loadCloud();}catch(error){window.dispatchEvent(new CustomEvent("printora:cloud-error",{detail:{error,context:"Материалы"}}));}}document.addEventListener("click",e=>{const managerBtn=e.target?.closest?.("[data-material-manager-open]");const card=e.target?.closest?.("[data-printora-material-card]");const add=e.target?.closest?.("[data-material-add]");if(managerBtn||card){e.preventDefault();ensureManager().hidden=false;renderList();}if(add){e.preventDefault();openModal();}});$("materialSelect")?.addEventListener("change",onSelect);renderList();populateSelect();getClient()?.auth?.onAuthStateChange?.(async(_event,session)=>{userId=session?.user?.id||null;loadLocal();if(userId){try{await loadCloud();}catch(error){window.dispatchEvent(new CustomEvent("printora:cloud-error",{detail:{error,context:"Материалы"}}));}}renderList();populateSelect();});}
  window.PRINTORA_MATERIALS={getAll:()=>materials.slice(),open:openModal,openManager:()=>{ensureManager().hidden=false;renderList();},getSelected:()=>window.PRINTORA_MATERIAL||null,refresh:async()=>{if(userId){try{await loadCloud();}catch(e){window.dispatchEvent(new CustomEvent("printora:cloud-error",{detail:{error:e,context:"Материалы"}}));}}renderList();populateSelect();}};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
